quarkus.datasource.db-kind = ${DB_KIND:mysql}
quarkus.datasource.username = ${DB_USERNAME:root}
# quarkus.datasource.password = ${DB_PASSWORD:l.MvT-0Re-.kVRx}
quarkus.datasource.password = ${DB_PASSWORD:ninosqliot24}
quarkus.datasource.jdbc.url = ${DB_JDBC_URL:jdbc:mysql://localhost:3306/health_insights}
# quarkus.datasource.jdbc.url = ${DB_JDBC_URL:jdbc:mysql://136.111.1.230/health_insights}

# En dev la BD es persistente ? Hibernate solo valida que el schema exista, no lo toca
quarkus.hibernate-orm.schema-management.strategy = ${DB_SCHEMA_STRATEGY:validate}
# import.sql ya no se ejecuta autom�ticamente; usar schema.sql manualmente
quarkus.hibernate-orm.sql-load-script = no-file
firebase.credentials=${FIREBASE_SERVICE_ACCOUNT_LOCATION:src/main/resources/healthinsights-c0fb5-firebase-adminsdk-fbsvc-73b60335f4.json}

quarkus.http.auth.proactive=false

quarkus.http.cors.enabled=true
# quarkus.http.cors.origins = https://frontend-health-391049646172.us-central1.run.app
quarkus.http.cors.origins = http://localhost:5173
quarkus.http.cors.methods = GET, PUT, POST, DELETE, PATCH
quarkus.http.cors.headers=Authorization,Content-Type
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-allow-credentials=true

# En test s� hacemos drop-and-create con H2 en memoria
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE
%test.quarkus.datasource.jdbc.driver=org.h2.Driver
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.sql-load-script=import.sql   
